<a href="https://colab.research.google.com/github/ysneef/THToanCaoCap/blob/main/ThucHanhChuong5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

th1 


In [ ]:
x= 3 
print (x)

3


In [ ]:
import math
x = math.sqrt(1+x)
print (x)

2.0


th2

In [ ]:
x = 3
lap = 1 
while (x!= math.sqrt (x+ 1)):
  x = math.sqrt(x +1 )
  lap + lap + 1 
  

In [ ]:
print (x)

1.618033988749895


In [ ]:
print (lap)

1


th3

In [ ]:
from sympy.core.singleton import S
import sympy as sp 
from sympy import Symbol
x = Symbol('x')
sp.solve(x-sp.sqrt(1+x),x)

[1/2 + sqrt(5)/2]

th4 

In [ ]:
import numpy as np
v1 = np.array([1.,2.,3.]) # tạo vecto 3 chiều
v2 = np.array ([2.,1.,0.])
# cộng vecto
v3 = v1 + v2 
print (v3)

[3. 3. 3.]


thực hiện phép toán tên vecto


In [ ]:
3*v1 + 2*v2 

array([7., 8., 9.])

In [ ]:
[1,2,3]+[2,1,0]

[1, 2, 3, 2, 1, 0]

In [ ]:
3*[1,2,3]+2*[2,1,0]

[1, 2, 3, 1, 2, 3, 1, 2, 3, 2, 1, 0, 2, 1, 0]

ghép nối các vecto

In [ ]:
v4 = np.hstack([v1, v2 ])
v4

array([1., 2., 3., 2., 1., 0.])

nhân vô hướng 2 vecto

In [ ]:
np.dot(v1,v2)

4.0

tính sin của vecto


In [ ]:
angles = np.linspace(0, np.pi/2, 3 )
angles

array([0.        , 0.78539816, 1.57079633])

In [ ]:
np.sin(angles)

array([0.        , 0.70710678, 1.        ])